### ISSUE TITLE
Request for add package `dnscrypt-proxy` 

### ISSUE THREAD

**Issue by sadraiiali** [noql-net/debs#1]
Hello :) 

## Brief
Dnscrypt-proxy is a dns client which can connect to any type of dns server and provide a local dns server to resolve using them.

Lang = 'GO'
CI/CD = ✅ 

## Links
* [Github](https://github.com/DNSCrypt/dnscrypt-proxy)
* [Website](https://dnscrypt.info/)
* [Debian Package](https://packages.debian.org/buster/dnscrypt-proxy)

**Comment by markpash** [comment]
added package `dnscrypt-proxy2`
